# Project: Australian Unemployed Prediction
### Description:

Goal: explore and clean the data 
Tech: Python\
Library: panda 
Data Source: Australian Bureau of Statistics

Data:\
All groups CPI, index numbers and percentage changes.xlsx

### Library:

In [6]:
# install
# !pip install pandas openpyxl

In [7]:
import pandas as pd

### Files:

In [8]:
fileLocation = "D:\Working Station\Career & Project\Data\laber prediction\Original Data"
CPI_Monthlypath = fileLocation + "\\" + "CPI_MonthlyPercentageChange.xlsx"
EmployPopulationRatial_Path = fileLocation + "\\" + "EmploymentToPopulationRatio.csv"

Read files

In [9]:
CPI_MonthlyOriginal = pd.read_excel(CPI_Monthlypath, sheet_name = "Data1")
EmployPopulationRatial_Original = pd.read_csv(EmployPopulationRatial_Path)

### CPI_MonthlyPath

#### Observe and Analyse the dataset

In [10]:
CPI_MonthlyPath = CPI_MonthlyOriginal.copy()
CPI_MonthlyPath.head()

,Unnamed: 0,Contribution to All groups CPI Percentage Points Change from Previous Period ; All groups CPI ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Food and non-alcoholic beverages ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread and cereal products ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Cakes and biscuits ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Breakfast cereals ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Other cereal products ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Meat and seafoods ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Beef and veal ; Australia ;,...,Contribution to All groups CPI Percentage Points Change from Previous Period ; Education ; Australia ;.1,Contribution to All groups CPI Percentage Points Change from Previous Period ; Preschool and primary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Secondary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Tertiary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance and financial services ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance ; Australia ;.1,Contribution to All groups CPI Percentage Points Change from Previous Period ; Financial services ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Deposit and loan facilities (direct charges) ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Other financial services ; Australia ;
0,Unit,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,...,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
2,Data Type,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,...,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

Observation:\
Data set type - structural data, wide data sets
Size - 30rows X 133 columns
columns- first column contains the information of each rows without a column name which suppose to be the column names, including but not limited to Unit, series type, data type, etc. From the seconde column to the last column, the column name contains the industry, including all groups, non-alcoholic beverages, bread and cereal product, etc. 
Data types - the data sets contain categorical, numerical and datetime datasets

#### Data processing plan

Step1 - transfer the wide data to long.\
Step2 - extract the industries info and name the column industry.\
Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.\
Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.\

#### Step1 - transfer the wide data to long.

In [11]:
CPT_Wide = CPI_MonthlyPath.T

#### Step2 - extract the industries info and name the column industry.

In [12]:
CPT_Wide.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,2024-05-01 00:00:00,...,2025-04-01 00:00:00,2025-05-01 00:00:00,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00
Contribution to All groups CPI Percentage Points Change from Previous Period ; All groups CPI ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393725R,-0.2307,...,0.7401,-0.493,0.1449,1.312,-0.0755,0.4484,-0.0074,0.0157,0.9639,0.352
Contribution to All groups CPI Percentage Points Change from Previous Period ; Food and non-alcoholic beverages ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130395482V,0.0768,...,0.0676,0.0198,0.0756,0.062,0.0174,-0.0456,0.0258,0.0664,0.0661,0.0873
Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread and cereal products ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130391709C,0.0015,...,-0.0059,-0.0087,-0.0022,0.0109,0.0007,-0.0041,0.0013,0.0124,0.014,0.003
Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393207R,-0.0013,...,-0.0018,-0.0028,-0.0021,0.0007,-0.0003,-0.0005,0.0029,0.002,0.0028,0.002

In [13]:
CPT_Wide_resetIndex = CPT_Wide.reset_index()

In [14]:
CPT_Wide_resetIndex.head()

,index,0,1,2,3,4,5,6,7,8,...,20,21,22,23,24,25,26,27,28,29
0,Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,...,2025-04-01 00:00:00,2025-05-01 00:00:00,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00
1,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393725R,...,0.7401,-0.493,0.1449,1.312,-0.0755,0.4484,-0.0074,0.0157,0.9639,0.352
2,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130395482V,...,0.0676,0.0198,0.0756,0.062,0.0174,-0.0456,0.0258,0.0664,0.0661,0.0873
3,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130391709C,...,-0.0059,-0.0087,-0.0022,0.0109,0.0007,-0.0041,0.0013,0.0124,0.014,0.003
4,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393207R,...,-0.0018,-0.0028,-0.0021,0.0007,-0.0003,-0.0005,0.0029,0.002,0.0028,0.002

In [15]:
#make first row as column name
CPT_Wide_resetIndex.columns = CPT_Wide_resetIndex.iloc[0]
CPT_DropFirstRow = CPT_Wide_resetIndex.drop(0, axis = 0)

In [16]:
#name the first column industry
firstColumnName = CPT_DropFirstRow.columns[0]
rename = 'Industry'
CPT_rename = CPT_DropFirstRow.rename(columns = {firstColumnName:rename})

In [17]:
#reset index
CPT_Wide_resetIndex = CPT_rename.reset_index(drop=True)

In [18]:
#extract the industry
CPT_Wide_resetIndex['Industry'] = CPT_Wide_resetIndex['Industry'].str.split(' ; ', expand=True)[1]

#### Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.

In [19]:
CPT_Wide_resetIndex.columns[10:]

Index([2024-05-01 00:00:00, 2024-06-01 00:00:00, 2024-07-01 00:00:00,
       2024-08-01 00:00:00, 2024-09-01 00:00:00, 2024-10-01 00:00:00,
       2024-11-01 00:00:00, 2024-12-01 00:00:00, 2025-01-01 00:00:00,
       2025-02-01 00:00:00, 2025-03-01 00:00:00, 2025-04-01 00:00:00,
       2025-05-01 00:00:00, 2025-06-01 00:00:00, 2025-07-01 00:00:00,
       2025-08-01 00:00:00, 2025-09-01 00:00:00, 2025-10-01 00:00:00,
       2025-11-01 00:00:00, 2025-12-01 00:00:00, 2026-01-01 00:00:00],
      dtype='object', name=0)

In [20]:
#Get the columns that are not CPT with dates
CPT_nonDateColumnNames = CPT_Wide_resetIndex.columns[:10].tolist()
CPT_nonDateColumnNames

['Industry',
 'Unit',
 'Series Type',
 'Data Type',
 'Frequency',
 'Collection Month',
 'Series Start',
 'Series End',
 'No. Obs',
 'Series ID']

In [21]:
#Melt the dataframe
CPT_MeltedDateTime = pd.melt(CPT_Wide_resetIndex, id_vars=CPT_nonDateColumnNames, var_name = 'DateTime', value_name = 'CPT_Changes')

In [22]:
CPT_MeltedDateTime.head()

,Industry,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,DateTime,CPT_Changes
0,All groups CPI,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393725R,2024-05-01,-0.2307
1,Food and non-alcoholic beverages,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130395482V,2024-05-01,0.0768
2,Bread and cereal products,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130391709C,2024-05-01,0.0015
3,Bread,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393207R,2024-05-01,-0.0013
4,Cakes and biscuits,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130399329W,2024-05-01,0.0022

In [23]:
CPT_MeltedDateTime['Year'] = CPT_MeltedDateTime['DateTime'].dt.year

In [24]:
CPT_MeltedDateTime['Month'] = CPT_MeltedDateTime['DateTime'].dt.month

In [25]:
CPT_MeltedDateTime.head()

,Industry,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,DateTime,CPT_Changes,Year,Month
0,All groups CPI,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393725R,2024-05-01,-0.2307,2024,5
1,Food and non-alcoholic beverages,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130395482V,2024-05-01,0.0768,2024,5
2,Bread and cereal products,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130391709C,2024-05-01,0.0015,2024,5
3,Bread,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393207R,2024-05-01,-0.0013,2024,5
4,Cakes and biscuits,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130399329W,2024-05-01,0.0022,2024,5

#### Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.

In [26]:
CPT = CPT_MeltedDateTime.copy()

In [27]:
CPT['No. Obs'].unique()

array([21], dtype=object)

Remove Unit, Series Type, Data Type, Frequency, Collection Month, No.Obs, because there is only one value in these columns

In [28]:
dropedColumns = ['Unit', 'Series Type', 'Data Type', 'Frequency', 'Collection Month', 'No. Obs']

In [29]:
CPT_DropedColumns = CPT.drop(columns = dropedColumns, axis = 1)

Also dropped Series Start, Series end and Series ID cause its not relavant to CPT changes. Dropped DateTime Cause we already have Year and Month

In [30]:
dropedColumns = ['Series Start', 'Series End', 'DateTime', 'Series ID']

In [31]:
CPT_DropedDates = CPT_DropedColumns.drop(columns = dropedColumns, axis = 1)

In [32]:
CPT_DropedDates.shape

(2772, 4)

### Employment to population Ration

#### Observe and Analyse the dataset

In [34]:
EmployPopulationRatial_Original

                                                             Employment-to-population ratio
NaN                                                Trend (%)        Seasonally adjusted (%)
Jan-16                                             61.4                                61.3
Feb-16                                             61.3                                61.3
Mar-16                                             61.3                                61.3
Apr-16                                             61.3                                61.2
...                                                                                     ...
Nov-25                                             63.9                                63.8
Dec-25                                             63.9                                64.0
Jan-26                                             64.0                                63.9
Large month-to-month changes occurred during th... NaN                                  NaN
Source: Australian Bureau of Statistics, Labour... NaN                                  NaN

[124 rows x 1 columns]

In [85]:
EmployPopulationRatial = EmployPopulationRatial_Original.copy()

Observation:\
The size of the data set is 124X1. The only column is named Employment-to-population ratio. Under the column there are three sub-columns. The first column is datetime, and the rest are the numerical data. The last two rows are not the value of the datasets.

#### Data processing plan

Step1 - reset index and the column names.\
Step2 - remove the last two rows.\
Step3 - extract month and year.

#### Step1 - reset index and the column names.

In [98]:
EmployPopulationRatial_ResetIndex = EmployPopulationRatial.reset_index()

In [99]:
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetIndex.copy()
EmployPopulationRatial_ResetColumnName.columns = EmployPopulationRatial_ResetColumnName.iloc[0].tolist()
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.iloc[1:]

In [100]:
OriginalColumnNames = EmployPopulationRatial_ResetColumnName.columns
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.rename(columns = {OriginalColumnNames[0]:'Date', OriginalColumnNames[1]:'Employment_Population_Ratio', OriginalColumnNames[2]:'Ratio_SeasonallyAdjusted'})

In [101]:
EmployPopulationRatial_ResetColumnName.head()

     Date Employment_Population_Ratio Ratio_SeasonallyAdjusted
1  Jan-16                        61.4                     61.3
2  Feb-16                        61.3                     61.3
3  Mar-16                        61.3                     61.3
4  Apr-16                        61.3                     61.2
5  May-16                        61.2                     61.1

#### Step2 - remove the last two rows.

In [103]:
EmployPopulationRatial_RemovedRows = EmployPopulationRatial_ResetColumnName.iloc[:121] 
EmployPopulationRatial_RemovedRows

       Date Employment_Population_Ratio Ratio_SeasonallyAdjusted
1    Jan-16                        61.4                     61.3
2    Feb-16                        61.3                     61.3
3    Mar-16                        61.3                     61.3
4    Apr-16                        61.3                     61.2
5    May-16                        61.2                     61.1
..      ...                         ...                      ...
117  Sep-25                        64.0                     63.9
118  Oct-25                        63.9                     64.0
119  Nov-25                        63.9                     63.8
120  Dec-25                        63.9                     64.0
121  Jan-26                        64.0                     63.9

[121 rows x 3 columns]

#### Step3 - extract month and year.

In [139]:
EmployPopulationRatial_ExtractMonthYear = EmployPopulationRatial_RemovedRows.copy()

In [140]:
MonthYear = EmployPopulationRatial_ExtractMonthYear['Date'].str.split('-', expand=True)

In [141]:
MonthYear.columns

RangeIndex(start=0, stop=2, step=1)

In [142]:
EmployPopulationRatial_ExtractMonthYear['Month_Name'] = MonthYear[0]
EmployPopulationRatial_ExtractMonthYear['Year'] = MonthYear[1]

In [144]:
EmployPopulationRatial_ExtractMonthYear['Month'] = pd.to_datetime(EmployPopulationRatial_ExtractMonthYear['Month_Name'], format='%b').dt.month

In [146]:
# drop Date, Month_Name
EmployPopulationRatial = EmployPopulationRatial_ExtractMonthYear.drop(columns = ['Date', 'Month_Name'])

In [147]:
EmployPopulationRatial.head()

  Employment_Population_Ratio Ratio_SeasonallyAdjusted Year  Month
1                        61.4                     61.3   16      1
2                        61.3                     61.3   16      2
3                        61.3                     61.3   16      3
4                        61.3                     61.2   16      4
5                        61.2                     61.1   16      5